[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_PINATA_API_KEY = "ecd85e82737a589c9f9b"
  REACT_APP_PINATA_API_SECRET = "780bb379526f298fea100952b2159e8238a06e67e580f3de0cf5a199cb5fd3e8"
  REACT_APP_FIREBASE_API_KEY = "AIzaSyAGIdvoOJUkOxk_jbMB1io7cP813rK3c7g"
  REACT_APP_FIREBASE_AUTH_DOMAIN = "marketmate-37ee5.firebaseapp.com"
  REACT_APP_FIREBASE_PROJECT_ID = "marketmate-37ee5"
  REACT_APP_FIREBASE_STORAGE_BUCKET = "marketmate-37ee5.appspot.com"
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID = "1010355181989"
  REACT_APP_FIREBASE_APP_ID = "1:1010355181989:web:02dfd231bf2ab0e2ee304c"
  REACT_APP_FIREBASE_MEASUREMENT_ID = "G-9VVB385FR2"
